### ISSUE TITLE
pipes-zlib failing to decompress zlib correctly?

### ISSUE THREAD

**Issue by vaibhavsagar** [k0001/pipes-zlib#19]
I'm trying to generate a git packfile index from a packfile for my library: https://github.com/vaibhavsagar/duffer/blob/pipes-experiment/src/Duffer/Pack/Streaming.hs. I think the logic is correct and it does seem to generate the correct output for the first couple of entries, but then it fails with `ZlibException (-3)` as demonstrated here: https://github.com/vaibhavsagar/duffer/blob/pipes-experiment/Pipes.ipynb. I believe this might be an issue with the library, is this the case or is there an error somewhere in my code?

**Comment by k0001** [comment]
Any chance this could be related to your usage of the 'Pipes.Zlib' module
instead of the 'Pipes.GZip' module? Maybe Gzip, and not plain Zlib, is the
expected format.

**Comment by vaibhavsagar** [comment]
Thanks for getting back to me! No, that's not a concern, as `git` packfiles are partially zlib-compressed.

**Comment by vaibhavsagar** [comment]
I suspect this might be because the library is incorrectly reading in and trying to decompress too much content, but I also have no way to tell it to stop after a certain length when decompressed (which is provided in the packfile entry).

**Comment by k0001** [comment]
Are you saying that the original `ByteString` stream is not 100% ZLib compressed? In that case you should use `pipes-bytestring` to limit the length of the stream you pass in to `pipes-zlib`. You'll need to know the number of compressed bytes you are supposed to be decompressing, but that information will likely be part of the git packfile format.

Presumably `decompress'` gives you access to leftovers after the compressed stream ends, but maybe the “compressed stream” present in the git packfiles you are trying to parse don't have proper delimiters or something like it.

**Comment by vaibhavsagar** [comment]
`git` packfile entries are not delimited, but I believe `pipes-zlib` should handle this correctly. The entries also don't have the length of the compressed content, only its length after decompression, which is why I'm using `pipes-zlib` in the first place.

**Comment by vaibhavsagar** [comment]
If I had a function for "decompress until the decompressed content reaches this length" then I could use that, but `pipes-zlib` doesn't offer this.

**Comment by vaibhavsagar** [comment]
Here are more details on packfiles if you're interested: http://stefan.saasen.me/articles/git-clone-in-haskell-from-the-bottom-up/#pack_file_format

**Comment by vaibhavsagar** [comment]
Actually, looking at the linked article again, I think I know what is going on and it may be a bug in my code. I will have a look again and update this issue when I find out. Sorry for the hassle!

**Comment by vaibhavsagar** [comment]
I was handing `pipes-zlib` bad data (not account for offsets/refs in delta entries) so this is not a bug in the library. Thanks for being so patient with me :smile:
