### ISSUE TITLE
notice when we have a truncated archive

### ISSUE THREAD

**Issue by dimbleby** [k0001/pipes-zlib#28]
Currently decompression based on `pipes-zlib` doesn't notice if it is given a truncated archive: it just decompresses what it can and reports no error.

As of 0.1.18 `streaming-commons` exposes an interface allowing this case to be spotted, by asking the inflater whether or not it thinks that it is done.  If we run out of input while the inflater is expecting more, then the archive was truncated.

I'd prefer to get #27 sorted first because of the refactoring involved, but once we're agreed what to do with that I hope to submit a pull request along [these lines](https://github.com/dimbleby/pipes-zlib/commit/7907fcf690b9037b32a549c7a9a3134f5e1078e2).

**Comment by dimbleby** [comment]
Looks like you've done something like this without even needing to wait for my pull request - thanks!

**Comment by k0001** [comment]
@dimbleby I cherry-picked your commit :) Thank you.
