### ISSUE TITLE
Compatibility with GHC 9.2

### ISSUE THREAD

**Issue by bgamari** [k0001/pipes-zlib#34]
0.4.4.2 can not be built with GHC 9.2 due to simplified subsumption. Also, the version number in `master` is currently behind that on Hackage.

**Comment by bgamari** [comment]
As an aside, I would be happy to help maintain this package. I have a project which depends upon it and have been essentially maintaining a local fork for years now.

**Comment by k0001** [comment]
Fixed, and thank you for the offer! I just added you as a collaborator.
