### ISSUE TITLE
Improve zlib-bindings or stop relying on it

### ISSUE THREAD

**Issue by k0001** [k0001/pipes-zlib#5]
The `zlib-bindings` library requires that we run on top of the `IO` monad, and we'd rather not require that.

**Comment by arianvp** [comment]
http://hackage.haskell.org/package/zlib-0.5.4.1/docs/Codec-Compression-Zlib.html seems to provide a pure interface. Maybe we should look at that.

**Comment by k0001** [comment]
@arianvp it doesn't look like the `zlib` library supports compressing and decompressing in a streaming fashion, but maybe there are some tricks hidden in its `Codec.Compression.Zlib.Internal` module. Perhaps `zlib` can be extended with a nice API to support just that.

But by all means, please go ahead with these changes if you find that it is possible to do so using `zlib`.

**Comment by k0001** [comment]
We are now relying on `streaming-commons` instead of `zlib-bindings`. A `IO`-less backend would be better, but nobody has implemented one yet. I'll close this for the time being.
